### PR TITLE
Problem: fails to compile with signatory 0.16

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution: update signature to version 0.16 and use signature crate 1.0.0-pre.1

### CODE REVIEW

**Comment by Liamsi** [comment]
Could you re-commit with a GPG signed commit and force push? Otherwise we can't merge currently.

**Comment by Liamsi** [comment]
Since recently this started failing with: 

```
  Compiling ed25519-dalek v1.0.0-pre.3
error[E0432]: unresolved import `rand`
  --> /Users/ismail/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/ed25519.rs:14:5
   |
14 | use rand::{CryptoRng, RngCore};
   |     ^^^^ use of undeclared type or module `rand`

error[E0432]: unresolved import `rand`
  --> /Users/ismail/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/secret.rs:22:5
   |
22 | use rand::{CryptoRng, RngCore};
   |     ^^^^ use of undeclared type or module `rand`

error: aborting due to 2 previous errors

```
This is unrelated to the changes made here. I ran into the same issue in https://github.com/interchainio/tendermint-rs/pull/63#issuecomment-563572455
I would still hold off merging this until we resolved the issue that causes this.

**Comment by tarcieri** [comment]
Looks like it's due to an upstream release of `ed25519-dalek`. I would guess that including it in `Cargo.toml` with the `rand` feature enabled would fix it (or locking to the previous prerelease).

**Comment by Liamsi** [comment]
Thanks @tarcieri! That works! I'll fix master in a bit and then merge in this PR.

**Comment by Liamsi** [comment]
Just for my understanding. This is due to the `rand` feature which used to be a default feature and is not anymore?

**Comment by tarcieri** [comment]
I think it's an upstream regression

**Comment by tarcieri** [comment]
@linfeng-crypto can you rebase?

**Comment by Liamsi** [comment]
Superseded by #89
